### ISSUE TITLE
혹시 디테일한 배포를 생각하고 계시다면 requirements 디렉토리를 생성하셔서, requirements.txt를 생성해보세요

### ISSUE THREAD

**Issue by leopard627** [seoweon/dart_reports#2]
# @seoweon 

이렇게 된다면 다른분들이 더 편하게 이 프로젝트를 테스트 해보실수 있을겁니다. 🥇 

pip freeze > requirements.txt 또는 developmet.txt

requirements/ requirements.txt  또는 developments.txt   ##...등등...

**Comment by seoweon** [comment]
아맞다! 퇴근하고 추가할게요! 감사합니다 👍 👍

**Comment by seoweon** [comment]
requirements.txt 추가되었습니다! 😄
